spring:
  application:
    name: ${ZUUL_NAME}
server:
  port: ${ZUUL_PORT}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}
  instance:
    prefer-ip-address: true
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 60000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 60000
zuul:
  routes:
    caicloud-provider-user: /user/**
